sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: SVq6yHfw9g3d3PgaQ3I8eIIJgmrKBQpBKb2g2tkgSO0vpy0JKKIwsdjCWwAqYN7dMnxacm2kYuatUFLNysqtE6VcuyZpHUmDyu5WcrSFuVOq2dcX5JXUSFfua0AKq1EvsmWU7qDvAle4OU7NsmpgA7+HcJIV3Yy9wOl5Tyo9b6ctrooy1ABzjSTeJRizN3COtDMqxPZfudHcICK7fH73LLmMorcKakq2lfEYQxekPWWzxNy3SiZdpct+g52fctNyeu5RmWqa+veZLJJZ2YbIfUgKBvDqFTbIrEEI30DxnPD1t5PcIjLwq1Q3GGH32SpHjbomnijcHiqg/EAJmwmiShSU0wYw9Q6P+ckKnX/6VM2/HGwFRgcMUieFoO77FvzRvD2nz0D8ErWr9FCmcRtG7RHK18cojKSHgumKNhNspVDhcPzsp1rmOG0VZc7Nci4/5SIYEc9OAPCKj2OtcXhCZd/kK+tOFQyO9bve69rOp2JIpYCFpgWVcdwbRqIrd6/9SvDTCdleWnV3CIz9rpEStrA9eUCd2RIq5yvtOECQpSjZZuHwLDwjpD5F2gJhcpCzBaVJ3Vb3GgOHMYmAU75dzV9vQBX+PdczCxxysiwGo+19r1Ml9nRnRz3Vto/4zSxOMZMWiEDqt1sUyu/ahixRL+03jYwuPrRQur03CjQHRv0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Yorkshire-Dialect-Poems--1673-1915--and-traditional-poems_2888
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy